### ISSUE TITLE
xdg-shell-surface segfault

### ISSUE THREAD

**Issue by xiangzhai** [xiangzhai/orbital#1]
When resize, close, then segfault, the gdb bt shown as below:

```
[orbital debug] DEBUG: void Orbital::XdgShell::useUnstableVersion(wl_client*, wl_resource*, int32_t)
[orbital debug] DEBUG: Orbital::XdgShellSurface::XdgShellSurface(Orbital::ShellSurface*, wl_client*, uint32_t)
[orbital debug] DEBUG: void Orbital::XdgShellSurface::setTitle(wl_client*, wl_resource*, const char*) Wayland Terminal
[orbital debug] DEBUG: void Orbital::XdgShellSurface::setTitle(wl_client*, wl_resource*, const char*) Wayland Terminal
[orbital debug] DEBUG: void Orbital::XdgShellSurface::setWindowGeometry(wl_client*, wl_resource*, int32_t, int32_t, int32_t, int32_t) 32 32 662 517
[orbital debug] DEBUG: void Orbital::XdgShellSurface::setTitle(wl_client*, wl_resource*, const char*) zhaixiang@zhaixiang:/data/project/xiangzhai/orbital/build
[orbital debug] DEBUG: void Orbital::XdgShellSurface::resize(wl_client*, wl_resource*, wl_resource*, uint32_t, uint32_t)
[orbital debug] DEBUG: virtual Orbital::XdgShellSurface::~XdgShellSurface()

Program received signal SIGSEGV, Segmentation fault.
weston_view_from_global_float (view=0x6400000208, x=57, y=137, vx=0x7fffffffdb48, 
    vy=0x7fffffffdb4c) at src/compositor.c:1085
1085		if (view->transform.enabled) {
(gdb) bt
#0  weston_view_from_global_float (view=0x6400000208, x=57, y=137, vx=0x7fffffffdb48, 
    vy=0x7fffffffdb4c) at src/compositor.c:1085
#1  0x00007ffff74dadf6 in weston_view_from_global_fixed (view=<optimized out>, 
    x=<optimized out>, y=<optimized out>, vx=0x7fffffffdb9c, vy=0x7fffffffdb98)
    at src/compositor.c:1114
#2  0x000000000046eb54 in Orbital::View::mapFromGlobal (this=0xb38d00, p=...)
    at /data/project/xiangzhai/orbital/src/compositor/view.cpp:150
#3  0x0000000000466c0c in Orbital::ShellSurface::ResizeGrab::motion (this=0xb2e1b0, 
    time=280815302, x=57, y=142)
    at /data/project/xiangzhai/orbital/src/compositor/shellsurface.cpp:256
#4  0x000000000047712e in Orbital::PointerGrab::PointerGrab()::{lambda(weston_pointer_grab*, unsigned int, int, int)#2}::operator()(weston_pointer_grab*, unsigned int, int, int) const ()
    at /data/project/xiangzhai/orbital/src/compositor/seat.cpp:528
#5  0x000000000047718e in Orbital::PointerGrab::PointerGrab()::{lambda(weston_pointer_grab*, unsigned int, int, int)#2}::_FUN(weston_pointer_grab*, unsigned int, int, int) ()
    at /data/project/xiangzhai/orbital/src/compositor/seat.cpp:530
#6  0x00007fffebc27bcb in x11_backend_deliver_motion_event (event=<optimized out>, 
    b=<optimized out>) at src/compositor-x11.c:1086
#7  x11_backend_handle_event (fd=520, mask=4294957896, data=0x6d5670)
    at src/compositor-x11.c:1253
#8  0x00007ffff76ffc88 in post_dispatch_check (loop=0x6cf5e0) at src/event-loop.c:385
#9  wl_event_loop_dispatch (loop=0x6cf5e0, timeout=<optimized out>) at src/event-loop.c:425
#10 0x00007ffff74de120 in weston_output_repaint (output=<optimized out>) at src/compositor.c:1872
#11 weston_output_finish_frame (output=0x6400000208, output@entry=0x780e10, stamp=0x780e10)
    at src/compositor.c:1922
#12 0x00007fffebc27126 in x11_output_start_repaint_loop (output=0x780e10)
    at src/compositor-x11.c:346
#13 0x00007fffebc27139 in finish_frame_handler (data=<optimized out>) at src/compositor-x11.c:456
---Type <return> to continue, or q <return> to quit---
#14 0x00007ffff76ff679 in wl_event_source_timer_dispatch (source=0x778e60, ep=<optimized out>)
    at src/event-loop.c:179
#15 0x00007ffff76ffc42 in wl_event_loop_dispatch (loop=0x6ccf90, timeout=<optimized out>)
    at src/event-loop.c:419
#16 0x000000000045901d in Orbital::Compositor::processEvents (this=0x7fffffffe7a0)
    at /data/project/xiangzhai/orbital/src/compositor/compositor.cpp:393
#17 0x000000000045cc95 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Orbital::Compositor::*)()>::call(void (Orbital::Compositor::*)(), Orbital::Compositor*, void**) (
    f=(void (Orbital::Compositor::*)(Orbital::Compositor * const)) 0x458fec <Orbital::Compositor::processEvents()>, o=0x7fffffffe7a0, arg=0x7fffffffe450)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:500
#18 0x000000000045c91e in QtPrivate::FunctionPointer<void (Orbital::Compositor::*)()>::call<QtPrivate::List<>, void>(void (Orbital::Compositor::*)(), Orbital::Compositor*, void**) (
    f=(void (Orbital::Compositor::*)(Orbital::Compositor * const)) 0x458fec <Orbital::Compositor::processEvents()>, o=0x7fffffffe7a0, arg=0x7fffffffe450)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:519
#19 0x000000000045c1fd in QtPrivate::QSlotObject<void (Orbital::Compositor::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, 
    this_=0x76d580, r=0x7fffffffe7a0, a=0x7fffffffe450, ret=0x0)
    at /usr/include/qt/QtCore/qobject_impl.h:143
#20 0x00007ffff7bc58fa in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQt5Core.so.5
#21 0x00007ffff7c438ae in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) ()
   from /usr/lib/libQt5Core.so.5
#22 0x00007ffff7bd38db in QSocketNotifier::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff7b966ac in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#24 0x00007ffff7bee255 in ?? () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff50f9a0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff50f9cf8 in ?? () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff50f9dac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff7bedca7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#29 0x00007ffff7b94162 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#30 0x00007ffff7b9bb3c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#31 0x0000000000454387 in main (argc=1, argv=0x7fffffffeb08)
    at /data/project/xiangzhai/orbital/src/compositor/main.cpp:71
(gdb) q
A debugging session is active.

	Inferior 1 [process 9855] will be killed.

Quit anyway? (y or n) y
[orbital-client warning] The Wayland connection broke. Did the Wayland compositor die?
[orbital warning] The Wayland connection broke. Did the Wayland compositor die?
[orbital-client warning] The Wayland connection broke. Did the Wayland compositor die?
[orbital warning] The Wayland connection broke. Did the Wayland compositor die?
```

**Comment by xiangzhai** [comment]
Fixed https://github.com/xiangzhai/orbital/commit/7199f3b181f7d669d162258d1ca203b3d56b3925 thank @giacum

But there are still a lot of thing I need to learn ;P
